changes for flow
iCargopoc/library pull request #165
Opened 2020-12-28 09:56 UTC by Eldho-Abraham

2020-12-28 13:18 UTC, iCargopoc requested changes

2020-12-28 13:18 UTC, iCargopoc commented on grid/src/index.js
> +        searchText: Object
searchText is a string

2020-12-28 13:18 UTC, iCargopoc commented on grid/src/index.js
> +        isSubComponentRow: Object
isSubComponentRow is boolean

2020-12-28 13:18 UTC, iCargopoc commented on grid/src/index.js
> +        compareOrder: Object,
compareOrder is string

2020-12-28 13:18 UTC, iCargopoc commented on grid/src/index.js
> +                let sortedTreeData = [null];
[null] should not be used

2020-12-29 04:20 UTC, Eldho-Abraham commented on grid/src/index.js
> +        searchText: Object
done

2020-12-29 04:20 UTC, Eldho-Abraham commented on grid/src/index.js
> +        compareOrder: Object,
done

2020-12-30 11:37 UTC, iCargopoc requested changes

2020-12-30 11:37 UTC, iCargopoc commented on grid/src/index.js
> +const processedData = (gridData: Object, parentIdAttribute: Object): ?[] => {
gridData will be an array

2020-12-30 11:37 UTC, iCargopoc commented on grid/src/index.js
> +        v1: Object,
v1 can be boolean/string/number etc...

2020-12-30 11:37 UTC, iCargopoc commented on grid/src/index.js
> +        v2: Object
v2 can be boolean/string/number etc...

2020-12-30 11:37 UTC, iCargopoc commented on grid/src/index.js
> +        originalData: Object,
originalData will be array

2020-12-30 11:37 UTC, iCargopoc commented on grid/src/index.js
> +        groupSortOptions: Object
groupSortOptions will be array

2020-12-30 11:58 UTC, Eldho-Abraham commented on grid/src/index.js
> +        v1: Object,
object will be generic

2020-12-30 11:59 UTC, Eldho-Abraham commented on grid/src/index.js
> +        v2: Object
object will be generic

2020-12-30 12:00 UTC, Eldho-Abraham commented on grid/src/index.js
> +        originalData: Object,
done

2021-01-04 08:41 UTC, Eldho-Abraham commented on grid/src/index.js
> +        groupSortOptions: Object
done

2021-01-07 06:43 UTC, closed without merging